networks:
  app-network:

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es-container
    environment:
      - node.name=single-node
      - cluster.name=goods
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  goodsapp:
    image: heechannoh/goods-project-image:latest  # Docker Hub에 올린 애플리케이션 이미지
    container_name: goodsApp
    depends_on:
      redis:
        condition: service_healthy
      es:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network